# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: specialty.hu - heti hírek a kávé világából
email: info@specialty.hu
description: > # this means to ignore newlines until "baseurl:"
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas hendrerit massa vel interdum vestibulum.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://specialty.hu" # the base hostname & protocol for your site
twitter_username: specialty.hu
#github_username:  

# Build settings
markdown: kramdown
